### PR TITLE
Fix favicon loading so it does not block data storage

### LINKED ISSUE #137: [BUG] Top Site Detail shows "undefined" after visiting a site for a very short period of time
**Describe the bug**
Top site detail incorrectly shows the text "undefined". 

**To Reproduce**
1. Remove Akita if you already have it installed
2. Install Akita and Coil, pay for Coil (not sure if coil is necessary)
2. In the Akita browser extension pop-up tutorial click on the "puma browser" link
3. Observe that the puma web browser website opens
4. Open the akita browser extension and observe that the puma web browser website does not show in top sites (sleepy akita should be showing).
5. Navigate to a web monetized site like akitaproject.site
6. Open the akita browser extension and observe that the puma web browser website and akitaproject.site show up in top sites.
7. Hover over the puma browser top site circle and see the text "undefined"

**Expected behavior**
In reproduction step 6 the puma web browser website should have shown in top sites. In step 7 the text should say something like "You've spent _ second of monetized time here ..." but it says "undefined"

**Screenshots**

**Desktop (please complete the following information):**
 - OS and Version: macOS 11.2
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by vezwork**
Fixes #137 [BUG] Top Site Detail shows "undefined" after visiting a site for a very short period of time

## Changes

- Removes the `await` from the `updateOriginFavicon` function call in the `updateAkitaData` function definition in `storage.js`. This `await` was causing an issue because the `updateOriginFavicon` function awaits a fetch on the favicon image which may take an indefinite time to complete, blocking the function and in-turn indefinitely blocking data storage in the `updateAkitaData` function.
- Adds text display handling for when `visitCount`or `timeSpent` are 0.

### CODE REVIEW

File: src/popup/popup.js [hunk 1]
```diff
@@ -384,25 +384,20 @@ function createTopSiteDetailEls(originData, originStats) {
...
+	// Set visit count text
 	let visitCountEl = paragraphEl();
-	if (visitCountText !== ``) {
+	if (visitCount > 0) {
 		const percentVisits = getPercentVisitsToOriginOutOfTotal(originData, originStats);
 		if (percentVisits > 0) {
 			setContentOfEl(visitCountEl, [
 				textEl(`You've visited `),
-				strongEl(visitCountText),
+				strongEl(`${visitCount} time${visitCount > 1 ? `s` : `` }`),
```
Comment (sharon-wang) [inline src/popup/popup.js]: nit for readability:

I think pulling out the check to add the `s` to `time` would make this a bit more readable.

**Review by sharon-wang — CHANGES_REQUESTED** [review]

**Review by sharon-wang — APPROVED** [review]
lgtm!
