### PR TITLE
Fix originData favicon path not being stored

### LINKED ISSUE #148: [BUG] Favicons don't show up for newly visited sites
**Describe the bug**
Letters show up in place of favicons in the circles in the "Your Top Monetized Sites" section of extension popup. This indicates that the favicon URLs are not being stored.

**To Reproduce**
1. Re-install Akita in your browser of choice
2. Visit any monetized site e.g. https://akitaproject.site
3. Click the Akita icon in the browser toolbar to open the Akita popup
4. Observe that the circle corresponding to the monetized site you visit has a single letter in it rather than a favicon.

**Expected behavior**
The sites favicon should show up in the circle rather than a single letter.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS and Version: MacOS
 - Browser and Version: Chrome

**Additional context**
Probably related to the recent changes to favicon storage in PR #141.

### PR DESCRIPTION
**Pull request by vezwork**
Fixes #148

## Changes

- Renames `AkitaOriginData.storeOriginFavicon` to `AkitaOriginData.setOriginFavicon` (and all usages) to reflect that it updates the originData object rather than storing it in the browser's local storage.
- Removes the `updateOriginFavicon` function.
- Fixes #148 by adding a new function `storeOriginFavicon` in `storage.js` (Note that this function is not related to the renamed `AkitaOriginData.storeOriginFavicon` function)  which is called by `updateAkitaData` to asynchronously fetch, update, and store the favicon for an origin.

## Bug explanation

This bug is a regression introduced in #141.
This PR made it so that favicon fetching did not block storing originData. This resulted in a regression where the originData object was being updated after it had already been stored, meaning the updated originData object was never stored.

## Fix explanation

Fixing this issue requires introducing a new function `storeOriginFavicon` which fetches the favicon, and once/if the fetch resolves, updates and stores the originData safely using a lock.

## Fix demo image
image

### CODE REVIEW

File: src/data/storage.js [hunk 1]
```diff
@@ -83,7 +83,9 @@ async function storeDataIntoAkitaFormatNonMonetized(data, typeOfData) {
  * @param {Boolean} isMonetizedData Whether or not the data being stored is for a monetized origin.
  */
 async function updateAkitaData(originData, data, typeOfData, isMonetizedData) {
-	// TODO: ensure typeOfData is one of AKITA_DATA_TYPE
+	if (!Object.values(AKITA_DATA_TYPE).includes(typeOfData)) {
```
Comment (sharon-wang) [inline src/data/storage.js]: for readability, maybe we can create something like `const validAkitaDataTypes = Object.values(AKITA_DATA_TYPE)` and then do `validAkitaDataTypes.includes(typeOfData)`

File: src/data/storage.js [hunk 2]
```diff
@@ -107,16 +109,48 @@ async function updateAkitaData(originData, data, typeOfData, isMonetizedData) {
...
 	// Overwrite or create origin stats in storage
 	await storeOriginStats(originStats);
 }
 
+/**
+ * Given an origin and an absolute or relative path to a favicon, this function:
+ *   - fetches the favicon to check if it is a valid favicon,
+ *     - if the fetch is successful, the favicon is valid, so the origin's orginData favicon is set
+ *     to the given favicon path,
+ *     - if the fetch is unsuccessful the origin's originData favicon is set to "",
```
Comment (sharon-wang) [inline src/data/storage.js]: nitpick

```suggestion
 *     - if the fetch is unsuccessful, the origin's originData favicon is set to "",
```

File: src/data/storage.js [hunk 3]
```diff
@@ -107,16 +109,48 @@ async function updateAkitaData(originData, data, typeOfData, isMonetizedData) {
...
+ *   - finally, the updated originData is stored.
+ *
+ * Note: this function's implementation assumes that this origin's data has been created
```
Comment (sharon-wang) [inline src/data/storage.js]: nitpick

```suggestion
 * Note: this function's implementation assumes that the specified origin's data has been created
```

File: src/data/storage.js [hunk 4]
```diff
@@ -107,16 +109,48 @@ async function updateAkitaData(originData, data, typeOfData, isMonetizedData) {
...
+ * and stored prior to the critical section.
+ *
+ * @param {String} origin The origin which should have its corresponding originData favicon set.
```
Comment (sharon-wang) [inline src/data/storage.js]: rewording suggestion

```suggestion
 * @param {String} origin The origin to set a favicon for.
```

File: src/data/storage.js [hunk 5]
```diff
@@ -197,44 +231,48 @@ function updateTimeSpent(originData, originStats, recentTimeSpent, isMonetizedTi
...
- * is provided, construct the absolute path. Attempt to fetch the favicon to check
- * if it is a valid path. If fetch response is 200 OK, the path is valid, so store
- * the url of the favicon.
+ * Makes an absolute path from an input path which is either relative or absolute. If the input path
+ * is absolute, the input path is returned unchanged. If the input path is relative, an absolute
+ * path on the given origin is made with the input path.
  *
- * @param {AkitaOriginData} originData The origin data to update.
- * @param {String} faviconData The absolute or relative path to the site's favicon.
+ * @param {String} path A path which you want as an absolute path.
```
Comment (sharon-wang) [inline src/data/storage.js]: rewording suggestion

```suggestion
 * @param {String} path A path to convert to an absolute path, or check that it is already an absolute path.
```

File: src/data/storage.js [hunk 6]
```diff
@@ -197,44 +231,48 @@ function updateTimeSpent(originData, originStats, recentTimeSpent, isMonetizedTi
...
+ * @param {String} origin If the path is relative, This param is he origin which the path is
```
Comment (sharon-wang) [inline src/data/storage.js]:
```suggestion
 * @param {String} origin If the path is relative, this param is he origin which the path is
```

File: src/data/storage.js [hunk 7]
```diff
@@ -197,44 +231,48 @@ function updateTimeSpent(originData, originStats, recentTimeSpent, isMonetizedTi
...
-			if (200 === response.status) {
-				originData.storeOriginFavicon(faviconPath);
-			} else {
-				originData.storeOriginFavicon("");
-			}
+	if (response) {
+		if (200 === response.status) {
+			return true;
+		} else {
+			return false;
```
Comment (sharon-wang) [inline src/data/storage.js]:
```suggestion
		return (200 === response.status);
```

File: src/data/storage.js [hunk 8]
```diff
@@ -197,44 +231,48 @@ function updateTimeSpent(originData, originStats, recentTimeSpent, isMonetizedTi
...
+async function isFetchStatusOk(url) {
+	let response = await fetch(url);
 
-		if (response) {
-			if (200 === response.status) {
-				originData.storeOriginFavicon(faviconPath);
-			} else {
-				originData.storeOriginFavicon("");
-			}
+	if (response) {
```
Comment (sharon-wang) [inline src/data/storage.js]: if response is falsy, what do we expect this function to return?

**Review by sharon-wang — APPROVED** [review]
lgt moi
