### PR TITLE
Track monetized and non-monetized time properly

### LINKED ISSUE #79: [BUG] On sites with monetized AND non-monetized pages, non-monetized pages count for monetized time
**Describe the bug**
Once Akita sees that a site (domain) has a monetized page, it marks the entire domain as monetized. This is not accurate to how Web Monetization actually works. For example, Coil provides a mechanism for web monetizing youtube videos, once you visit a web monetized youtube video, Akita incorrectly counts ALL time on youtube as monetized time.
**To Reproduce**
1. Clear Akita data
2. Visit this web-monetized youtube video https://www.youtube.com/watch?v=sApKXmwhg4g&ab_channel=Simmer.io with an active Coil subscription and extension, and the Akita extension.
3. Spend 1 minute on the above youtube video.
4. Spend some extra time (let's say 5 mins) on other youtube videos which are not monetized. e.g. https://www.youtube.com/watch?v=F4we73GHH9k
5. Click on Akita extension icon and look at "Top monetized sites" section. Observe that youtube has 6 mins spent on it rather than 1.

**Expected behavior**
In the above reproduction Akita should only say that youtube has 1 minute spent on it, because while 6 mins were spent in total on the site, only 1 of those minutes was on a monetized page.

Akita should track both monetized and non-monetized time on a site seperately. For the purpose of the "Top monetized sites" section, only monetized time should be considered.

**Screenshots**
Unfortunately I do not have a screenshot.

**Desktop (please complete the following information):**
 - OS and Version: unknown
 - Browser and Version Chrome - version unknown

### PR DESCRIPTION
**Pull request by sharon-wang**
Fixes: #79 

Previously, we assumed that as soon as we see a payment pointer on a website (at an origin), that the origin is always considered to be monetized. So, once we decided that an origin is monetized, any time spent on the site was considered monetized time spent on the site. However, this is a flawed assumption, since sites such as YouTube may only contain payment pointers (meta tags) on specific videos and not others. So, some of the time spent on the site is monetized and some is non-monetized. This PR updates how we track time by checking for a payment pointer as we track time, to store
time spent properly.

We no longer store detailed data for every single origin -- only monetized origins are stored. Additionally, counting monetized
visits and associated functions have been removed as they were not being used or were redundant. The `isCurrentlyMonetized` field has been removed from AkitaOriginData as it was a major part of the problematic monetized time tracking. The text in the top site detail has been updated to point out that the time is monetized time, just to be clear.

### CODE REVIEW

**Comment by sharon-wang** [comment]
I've tested this with the Coil extension installed and I'm seeing the correct outcome.

### Test steps
1. Ensure Coil is installed and user is logged in
2. Install Akita from scratch (no existing data)
3. Go to a web monetized YouTube vid such as https://www.youtube.com/watch?v=sApKXmwhg4g&ab_channel=Simmer.io
4. Watch the video for X minutes
5. Open Akita
6. Hover on top site circle for YouTube, see that X minutes of monetized time on the site is indicated
7. Go to the YouTube homepage (not a monetized page) and stay there for Y minutes
8. Open Akita
9. Hover on top site circle for YouTube, see that X minutes of monetized time on the site is still indicated, since the Y minutes on the homepage do not count as monetized time

File: src/content_main.js [hunk 1]
```diff
@@ -104,42 +103,65 @@ async function trackTimeOnSite() {
 	let previousStoreTime = getCurrentTime();
```
Comment (vezwork) [inline src/content_main.js:113]: nit: rename to trackPaymentPointerAndTimeOnSite

File: src/main.js [hunk 2]
```diff
@@ -13,22 +13,22 @@
...
-		if (monetizedOriginDataList.length > 1) {
-			// Sort the list of origin data by timeSpentAtOrigin,
+	if (originDataList) {
+		if (originDataList.length > 1) {
+			// Sort the list of origin data by monetizedTimeSpent,
 			// i.e. sort by descending time starting from index 0
-			monetizedOriginDataList.sort((a, b) => {
-				return b.originVisitData.timeSpentAtOrigin - a.originVisitData.timeSpentAtOrigin
+			originDataList.sort((a, b) => {
+				return b.originVisitData.monetizedTimeSpent - a.originVisitData.monetizedTimeSpent
```
Comment (vezwork) [inline src/main.js]: nit: the idiomatic convention for an arrow function containing a single expression is to omit the curly braces and `return`.

`originDataList.sort((a, b) => b.originVisitData.monetizedTimeSpent - a.originVisitData.monetizedTimeSpent)`

File: src/main.js [hunk 3]
```diff
@@ -13,22 +13,22 @@
...
 			});
 
-			listSize = (listSize < monetizedOriginDataList.length) ? listSize : monetizedOriginDataList.length;
-			topOriginsList = monetizedOriginDataList.slice(0, listSize);
+			listSize = (listSize < originDataList.length) ? listSize : originDataList.length;
```
Comment (vezwork) [inline src/main.js]: nit: I think `listSize = Math.min(listSize, originDataList.length);` is more expressive.

**Comment by sharon-wang** [comment]
Also a note that you may need to install Akita from scratch again, since the data storage has changed. You might see weird behaviour in the UI otherwise.

File: src/main.js [hunk 4]
```diff
@@ -102,10 +102,10 @@ async function getTopOriginsThatNeedSomeLove(nTopOrigins) {
 				return sortResult;
 			});
 
-			listSize = (listSize < monetizedOriginDataList.length) ? listSize : monetizedOriginDataList.length;
-			topOriginsList = monetizedOriginDataList.slice(0, listSize);
+			listSize = (listSize < originDataList.length) ? listSize : originDataList.length;
```
Comment (vezwork) [inline src/main.js]: nit: I think `listSize = Math.min(listSize, originDataList.length);` is more expressive.

**Review by vezwork — COMMENTED** [review]
Going to test locally now. I have one question:

Currently you are counting any time on a page containing a monetization tag as monetized. I'm wondering what your thoughts are on instead not counting time as monetized until after the cachedPaymentPointer is validated? Then the monetized time would match more closely with the amount of time you see the monetized Akita extension icon, and invalid payment pointers would not count for monetized time.

File: src/main.js (hunk 2 above)
Comment (sharon-wang) [reply src/main.js]: Something like this?

```
	originDataList.sort((a, b) =>
		b.originVisitData.monetizedTimeSpent - a.originVisitData.monetizedTimeSpent
	);
```

**Comment by sharon-wang** [comment]
> Currently you are counting any time on a page containing a monetization tag as monetized. I'm wondering what your thoughts are on instead not counting time as monetized until after the cachedPaymentPointer is validated? Then the monetized time would match more closely with the amount of time you see the monetized Akita extension icon, and invalid payment pointers would not count for monetized time.

The cachedPaymentPointer would have already been validated 1 second prior (previous setInterval iteration). We could move setting `previousStoreTime = currentTime;` to after the paymentPointerOnPage is validated and `cachedPaymentPointer` is set to `paymentPointerOnPage`?

File: src/main.js (hunk 2 above)
Comment (vezwork) [reply src/main.js]: Yes! Nice code formatting I will have to do that next time I comment.

**Comment by vezwork** [comment]
> The cachedPaymentPointer would have already been validated 1 second prior (previous setInterval iteration). 

There is no garantee that the cachedPaymentPointer has been validated. For example: if `isPaymentPointerValid` was called to check if the cachedPaymentPointer was valid, but it came back as invalid, cachedPaymentPointer would still be non-null, or it's quite possible and even most likely that validation will take more than 1 second and cachedPaymentPointer would also be non-null in that case.

> We could move setting `previousStoreTime = currentTime;` to after the paymentPointerOnPage is validated and `cachedPaymentPointer` is set to `paymentPointerOnPage`?

I think something along these lines could work but my suggestion would be just to change [line 145](https://github.com/esse-dev/akita/pull/98/files#diff-510e4a7650a161c4553bf711c9dd68fa3cfbf6da8347a3ab20bf7c5c774b3918R145) to

```js
const isMonetizedTime = cachedPaymentPointer !== null && await isPaymentPointerRecentlyValidated(cachedPaymentPointer);
```
This should work, noting that time before the payment pointer is validated is not counted as monetized time even after the payment pointer is validated. I think this is reasonable since it is necessary to validate a payment pointer before monetization starts.

**Comment by vezwork** [comment]
Found a bug in my testing:

Github is showing up as a top monetized site although it shouldn't be. Strangely, the UI even says that github has no monetized time.
This is only happening after I visit another site which is actually monetized.

File: src/content_main.js [hunk 5]
```diff
@@ -100,46 +108,68 @@ async function trackVisitToSite() {
...
+		const paymentPointerOnPage = getPaymentPointerFromPage();
+
+		if (paymentPointerOnPage !== cachedPaymentPointer) {
+			const isValidPaymentPointer = await validatePaymentPointer(paymentPointerOnPage);
+
+			// Set the extension icon to monetized if the payment pointer is valid
+			setExtensionIconMonetizationState(isValidPaymentPointer);
+
+			// Update the cached payment pointer if the payment pointer on the page has changed
+			cachedPaymentPointer = isValidPaymentPointer ? paymentPointerOnPage : null;
```
Comment (sharon-wang) [inline src/content_main.js]: @vezwork I went a different route than what you suggested in https://github.com/esse-dev/akita/pull/98#issuecomment-751951147, but it should accomplish the same thing.

**Review by sharon-wang — COMMENTED** [review]
The new changes to `storeDataIntoAkitaFormat`/`storeDataIntoAkitaFormatNonMonetized` fixes the issue in https://github.com/esse-dev/akita/pull/98#issuecomment-751956776

File: src/content_main.js (hunk 5 above)
Comment (vezwork) [reply src/content_main.js]: Lines 160-170 cause the payment pointer to be re-validated if the already-started validation did not finish from when it started in the last setinterval step. Since validation can take multiple seconds, since it involves network requests, repeated validated will be common. I just tested and extra validation does happen.

I think this could be fixed by adding an extra flag, something like `isValidating` so validation is not repeated while its in process.

File: src/content_main.js [hunk 6]
```diff
@@ -186,78 +222,57 @@ function getPaymentPointerFromPage() {
...
-				paymentPointer: paymentPointer,
-				validationTimestamp: Date.now()
-			}, AKITA_DATA_TYPE.PAYMENT);
-			setExtensionIconMonetizationState(true);
+async function validatePaymentPointer(paymentPointer) {
+	let isValid = false;
+
+	if (paymentPointer) {
+		if (await isPaymentPointerRecentlyValidated(paymentPointer)) {
+			isValid = true;
```
Comment (vezwork) [inline src/content_main.js]: nit: I prefer early return i.e. `return true;`

File: src/content_main.js [hunk 7]
```diff
@@ -186,78 +222,57 @@ function getPaymentPointerFromPage() {
...
-			setExtensionIconMonetizationState(false);
+			// Validate if not validated recently
+			if (await isPaymentPointerValid(paymentPointer)) {
+				// Store the payment pointer and the UTC timestamp for the time it was validated (now)
+				await storeDataIntoAkitaFormat({
+					paymentPointer: paymentPointer,
+					validationTimestamp: Date.now()
+				}, AKITA_DATA_TYPE.PAYMENT);
+
+				isValid = true;
```
Comment (vezwork) [inline src/content_main.js:257]: nit: I prefer early return i.e. `return true;`

File: src/content_main.js [hunk 8]
```diff
@@ -186,78 +222,57 @@ function getPaymentPointerFromPage() {
...
+			}
 		}
 	}
+
+	return isValid;
```
Comment (vezwork) [inline src/content_main.js:276]: Then this would just be `return false`

**Review by vezwork — CHANGES_REQUESTED** [review]
Nice changes, I would say they improve the code quality and are clear. Just one issue about repeated validations otherwise this looks great.

**Comment by vezwork** [comment]
Just did some more testing and everything is working great :)

File: src/content_main.js (hunk 6 above)
Comment (sharon-wang) [reply src/content_main.js]: We should document this practice in #85

File: src/content_main.js (hunk 5 above)
Comment (sharon-wang) [reply src/content_main.js]: Don't we want the validation to occur though, since it could be validating a different payment pointer? I feel like we'd need to set up some sort of validation queue otherwise and probably integrate it with `isPaymentPointerRecentlyValidated()`?

Comment (vezwork) [reply src/content_main.js]: If we use a flag to wait for validation of a payment pointer to finish, we still ensure that we validate all new/different payment pointers: If we wait for validation of a payment pointer to finish, it will then be set as the `cachedPaymentPointer` (if it is valid), and the next time the setinterval step happens, the new payment pointer on the page will not `=== cachedPaymentPointer` so it will then be validated. This method won't miss validating different payment pointers, but it could involve extra waiting.

A validation queue sounds like it could work. Alternatively could have a variable `validatingPaymentPointer` which contains the payment pointer being validated, if a new/different payment pointer shows up, then you can start validating it otherwise you don't revalidate a payment pointer if it is the same as `validatingPaymentPointer`.

Comment (sharon-wang) [reply src/content_main.js]: I see, I interpreted your initial comment as "if validation is in progress already, check the flag and skip validation so we don't repeat it"

But you're actually saying, "if validation is in progress and it's for the same payment pointer, wait for the in progress validation to be done, instead of kicking off a new validation." Is my understanding correct?

Comment (vezwork) [reply src/content_main.js]: Yes!

**Comment by vezwork** [comment]
Thanks for the changes, looks great! Please squash and merge.

**Review by vezwork — APPROVED** [review]
